version: 2
jobs:
  build:
    docker:
      - image: cjmash/79061fc82
      - image: circleci/node
    environment:
      - PROJECT_NAME: packer
      - CLOUDSDK_COMPUTE_ZONE: europe-west3-b
      - PROJECT_ID: packer-19241277
    working_directory: ~/vof
    steps:
      - checkout
