version: 2
jobs:
  build:
    docker:
      - image: cjmash/79061fc8277
      - image: circleci/node
    environment:
      - PROJECT_NAME: packer
      - CLOUDSDK_COMPUTE_ZONE: europe-west3-b
      - PROJECT_ID: packer-19241277
    working_directory: ~/react
    steps:
      - checkout
      - run:
          name: install yarn update
          command:  sudo npm install yarn -g
      - run:
          name: install dependencies
          command: yarn install
  test:
    docker:
      - image: cjmash/79061fc8277
      - image: circleci/node
    working_directory: ~/react
    steps:
      - checkout
      - run:
          name: install yarn update
          command:  sudo npm install yarn -g
      - run:
          name: install dependencies
          command: yarn install
      - run:
          name: run tests
          command: sudo yarn test
  deploy_staging:
    docker:
      - image: cjmash/79061fc8277
      - image: circleci/node
    steps:
      - checkout
      - deploy:
          name: deploy our project to the staging cloud
          command: |
            if [ "${CIRCLE_BRANCH}" == "develop" ]; then
                bash .circleci/deploy.sh
            fi
  deploy_production:
    docker:
      - image: cjmash/79061fc8277
      - image: circleci/node
    steps:
      - checkout
      - deploy:
          name: deploy our project to the  production cloud
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                bash .circleci/deploy.sh
            fi


workflows:
  version: 2
  build_and_test_approval_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy_staging:
          type: approval
          requires:
            - test
          filters:
            branches:
              only: develop
      - deploy_production:
          requires:
            - test
          filters:
            branches:
              only: master

