version: 2
jobs:
  build:
    docker:
      - image: cjmash/79061fc8277
      - image: circleci/node
    environment:
      - PROJECT_NAME: packer
      - CLOUDSDK_COMPUTE_ZONE: europe-west3-b
      - PROJECT_ID: packer-19241277
    working_directory: ~/react
    steps:
      - checkout
      - run:
        name: install yarn update
        command:  sudo apt-get install yarn
      - run:
        name: install dependencies
        command: yarn install
      - save-cache:
        key: dependency-cache-{{ checksum "package.json" }}
        paths:
          - .node_modules

  test:
    steps:
      - checkout
    docker:
      - image: cjmash/79061fc82
      - image: circleci/node

      run:
        name: test
        command: yarn tests




