version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    working_directory: ~/react
    steps:
      - checkout
      - run:
          name: install yarn update
          command: sudo npm install yarn -g
      - run:
          name: install dependencies
          command: |
            yarn install
  test:
    docker:
      - image: circleci/node
    working_directory: ~/react
    steps:
      - checkout
      - run:
          name: install yarn update
          command:  sudo npm install yarn -g
      - run:
          name: install dependencies
          command: yarn install
      - run:
          name: run tests
          command: sudo yarn test
  deploy_production:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: build a gke container
          command: |
            echo "create a docker image for cloud"
            docker build -t grc.io/${PROJECT_ID}/react-app:$CIRCLE_SHA1 .
            chmod +x deploycontainer.sh
            bash ./deploycontainer.sh
            echo "we're pushing here"
            gcloud docker -- push grc.io/${PROJECT_ID}/react-app:$CIRCLE_SHA1 .

workflows:
  version: 2
  build_and_test_approval_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy_staging:
          type: approval
          requires:
            - test
          filters:
            branches:
              only: develop
      - deploy_production:
          filters:
            branches:
              only: master

